export const projects = [
  {
    title: 'AMA Cloud',
    description: "Fullstack development of Siemens UK AMA Cloud internal Engineering Asset Management platform. The platform included a technical issue ticketing system, real-time reporting, project management, resourcing and forecasting.",
    image: '/images/covid.jpg',
    tags: ['TypeScript', 'AWS', 'Serverless', 'React/Redux'],
    source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    visit: 'https://project.vipuljha.com/covid/',
    id: 0,
  },
  {
    title: 'XEMUSimTool',
    description: "Greenfield development of novel train simulation tool for Siemens Mobility UK used for viability studies in +£1bn new fleet bids. Saved the Engineering department £37k/use in 3rd party simulation costs.",
    image: '/images/portfolio.jpg',
    tags: ['Python', 'OOP', 'Tkinter', 'Pandas', 'NumPy'],
    source: 'https://github.com/lordarcadius/website',
    visit: 'https://project.vipuljha.com/website/',
    id: 1,
  },
  {
    title: 'SCENT',
    description: "Cybersecuirty tool for monitoring devices on on private onboard networks. A web application prototype was created for the tool to display real-time network activity and stats.",
    image: '/images/abs.jpg',
    tags: ['C++', 'TypeScript', 'React', 'AWS', 'Linux'],
    source: 'https://github.com/lordarcadius/ABS-Tweaks',
    visit: 'https://forum.xda-developers.com/t/tweak-mod-arm-x86-project-dark-booster-abs-tweaks-v5-0-2-3-6-0-23-01-2016.3120404/',
    id: 2,
  },
  {
    title: 'EV Charging Infrastructure Analysis',
    description: "Conference Paper written with Siemens Mind Sphere Analytics Centre to analyse and forecast the uptake of EV’s in the UK based on geographical location. The study forecasted trends in EV uptake based on region, government funding and registration data.",
    image: '/images/eb.jpg',
    tags: ['Python', 'Jupyter Notebooks', 'Prophet', 'Plotly'],
    source: 'https://github.com/lordarcadius/electrablue_mido',
    visit: 'https://forum.xda-developers.com/t/kernel-mido-oreo-pie-electrablue-kernel-21-0-july-06-redmi-note-4.3655651/',
    id: 3,
  },
  {
    title: 'ETA Stocks',
    description: "Web application for tracking ETF stock price data and ETF profiling using Alpha Vantage free tier API.",
    image: '/images/snapit.jpg',
    tags: ['Java', 'Spring Boot', 'React', 'JavaScript'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    id: 3,
  },
  {
    title: 'SleepMode CCU',
    description: "Energy saving software modification to the Central Control Unit (CCU) of the Class 350 fleets in the UK. The modification saves up to £1M/year in energy costs for HVAC systems.",
    image: '/images/capps.jpg',
    tags: ['Logic Design', 'Harware', 'DOORS', 'Cybersecurity'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Aquired new skills while trying not to catch COVID-19', },
  { year: 2021, text: 'Survived COVID-19 and got my first Job at Primebook.', },
  { year: 2022, text: 'Completed B.Tech in Information Technology.', },
  { year: 2023, text: 'Year under progress....', },
];